const express = require('express');
const multer = require('multer');
const csv = require('csv-parser');
const XLSX = require('xlsx');
const fs = require('fs');
const Groq = require('groq-sdk');
const { Resend } = require('resend');
require('dotenv').config();

const router = express.Router();
const upload = multer({ dest: 'uploads/' });

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
const resend = new Resend(process.env.RESEND_API_KEY);

/**
 * @swagger
 * /api/upload:
 *   post:
 *     summary: Upload CSV/Excel file and get AI summary via email
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               file:
 *                 type: string
 *                 format: binary
 *               email:
 *                 type: string
 *     responses:
 *       200:
 *         description: Summary sent to email
 *       400:
 *         description: Bad request
 *       500:
 *         description: Server error
 */

const parseFile = (filePath, mimetype) => {
  return new Promise((resolve, reject) => {
    const results = [];
    if (mimetype === 'text/csv' || filePath.endsWith('.csv')) {
      fs.createReadStream(filePath)
        .pipe(csv())
        .on('data', (data) => results.push(data))
        .on('end', () => resolve(results))
        .on('error', reject);
    } else {
      try {
        const workbook = XLSX.readFile(filePath);
        const sheet = workbook.Sheets[workbook.SheetNames[0]];
        const data = XLSX.utils.sheet_to_json(sheet);
        resolve(data);
      } catch (err) {
        reject(err);
      }
    }
  });
};

const generateSummary = async (data) => {
    const prompt = `
      You are a sales analyst. Analyze this sales data and provide a professional executive summary.
      Include: total revenue, top performing products/regions, trends, and recommendations.
      Data: ${JSON.stringify(data.slice(0, 50))}
      Keep it concise and professional.
    `;
    const response = await groq.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
    });
    return response.choices[0].message.content;
  };

router.post('/upload', upload.single('file'), async (req, res) => {
  try {
    const { email } = req.body;

    if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
    if (!email) return res.status(400).json({ error: 'Email is required' });

    const data = await parseFile(req.file.path, req.file.mimetype);
    if (data.length === 0) return res.status(400).json({ error: 'File is empty or invalid' });

    const summary = await generateSummary(data);

    await resend.emails.send({
      from: 'onboarding@resend.dev',
      to: email,
      subject: 'Your Sales Insight Summary',
      html: `
        <h2>Sales Insight Summary</h2>
        <p>${summary.replace(/\n/g, '<br/>')}</p>
        <br/>
        <small>Generated by Sales Insight Automator</small>
      `,
    });

    fs.unlinkSync(req.file.path);
    res.json({ success: true, message: 'Summary sent to your email!' });

  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Something went wrong: ' + error.message });
  }
});

module.exports = router;